stages:
  - build
  - package
  - publish

build linux:
  stage: build
  image: rust
  script:
  - apt-get update
  - apt-get install -y libclang-3.9-dev libspeechd-dev
  - export CPATH=/usr/lib/llvm-3.9/lib/clang/3.9.1/include/
  - cargo build --release
  - mv target linux
  artifacts:
    paths:
    - linux
    expire_in: 1 day

package:
  stage: package
  script:
  - mkdir godot-tts
  - cp godot-tts.gdnlib.release godot-tts/godot-tts.gdnlib
  - mkdir -p godot-tts/target/release
  - cp linux/release/*.so godot-tts/target/release
  - cp LICENSE godot-tts
  - cp TTS.gd godot-tts.g* godot-tts
  artifacts:
    name: godot-tts
    paths:
    - godot-tts
    expire_in: 1 day

publish:
  stage: publish
  script:
  - echo Publishing...
  artifacts:
    name: godot-tts
    paths:
    - godot-tts
  only:
  - tags
