image: rust

stages:
  - test
  - publish

before_script:
  - apt-get update
  - apt-get install -y libclang-3.9-dev libspeechd-dev
  - export CPATH=/usr/lib/llvm-3.9/lib/clang/3.9.1/include/

test linux:
  stage: test
  script:
  - cargo test

publish:
  stage: publish
  script:
  - echo Publishing.
  only:
  - tags
