image: rust

stages:
  - build
  - publish

before_script:
  - apt-get update
  - apt-get install -y libclang-3.9-dev libspeechd-dev
  - export CPATH=/usr/lib/llvm-3.9/lib/clang/3.9.1/include/

build linux:
  stage: build
  script:
  - cargo build --release

publish:
  stage: publish
  script:
  - cp godot-tts.gdnlib.release godot-tts.gdnlib
  only:
  - tags
