image:
- Visual Studio 2017
- ubuntu

install:
  - cmd: appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - cmd: rustup-init -y --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - sh: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --default-host x86_64-unknown-linux-gnu
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y libspeechd-dev
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - sh: source $HOME/.cargo/env
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --release
  # - cmd: mkdir -p staging\godot-tts\target\release
  - cmd: copy target\release\*.dll staging\godot-tts\target\release
  # - cmd: cd staging
  # - cmd: 7z a ../windows.zip *
  - sh: cp godot-tts.gdns staging/godot-tts
  - sh: cp godot-tts.gdnlib.release staging/godot-tts/godot-tts.gdnlib
  - sh: cp target/release/libgodot_tts.so target/godot-tts/target/release
  - sh: cd target
  - sh: zip -r9 godot-tts.zip godot-tts/
  - sh: appveyor PushArtifact godot-tts.zip

cache:
  - target
  - staging
