image: Visual Studio 2017

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build

before_deploy:
  - cargo build --release
  - mkdir -p staging\godot-tts\target\release
  - copy target\release\*.dll staging\godot-tts\target\release
  - cd staging
  - 7z a ../%PROJECT_NAME%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%.zip
