name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt-get update
        sudo apt-get install -y libspeechd-dev
        cargo build --release --verbose
        mv target linux
    - uses: actions/upload-artifact@v1
      with:
        name: linux
        path: linux

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        choco install -y llvm
        cargo build --release --verbose
        move target windows
    - uses: actions/upload-artifact@v1
      with:
        name: windows
        path: windows

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: linux
    - uses: actions/download-artifact@v1
      with:
        name: windows
    - run: |
        mkdir godot-tts
        cp godot-tts.gdnlib.release godot-tts/godot-tts.gdnlib
        mkdir -p godot-tts/target/release
        cp linux/release/*.so godot-tts/target/release
        cp windows/release/*.dll godot-tts/target/release
        cp LICENSE godot-tts
        cp TTS.gd godot-tts.g* godot-tts
        cp godot-tts.gdnlib.release godot-tts/godot-tts.gdnlib
        rm godot-tts/*.release
        zip -r9 godot-tts.zip godot-tts
    - uses: actions/upload-artifact@v1
      with:
        name: godot-tts
        path: godot-tts.zip
